minor fixes

diff --git a/bin/db-size b/bin/db-size
--- a/bin/db-size
+++ b/bin/db-size
@@ -7,10 +7,15 @@
 # requires: drs
 
 . /usr/share/server-scripts/lib/init
-
 use_config_var "DB_SIZE_NAMES_FILE"
 use_config_var "DB_SIZE_SIZES_FILE"
 use_config_var "DB_SIZE_CACHE_MINS"
+
+command -v drall >/dev/null 2>&1 || {
+	echo >&2 "drall required but it's not installed, aborting."
+	echo >&2 "https://github.com/popstas/drall"
+	exit 1
+}
 
 dbs=""
 
