fix: lvm-extent xfs partitions

diff --git a/bin/lvm-extend b/bin/lvm-extend
--- a/bin/lvm-extend
+++ b/bin/lvm-extend
@@ -81,7 +81,7 @@ if [ -e "$lv" ]; then
         echo ""
         # 4. resize partition
         echotitle "4. resize partition"
-        resize2fs "$lv"
+        resize2fs "$lv" || echo "Failed, if you trying to resize XFS partition: xfs_growfs $lv"
         echo ""
         df -h
     else
@@ -95,3 +95,4 @@ if [ -e "$lv" ]; then
 else
     echo "$lv don't exists"
 fi
+
