feat(site-rm): delete user, delete php-fpm configs

diff --git a/bin/site-rm b/bin/site-rm
--- a/bin/site-rm
+++ b/bin/site-rm
@@ -8,6 +8,7 @@ SCRIPT_HELP="site-rm /path/to/site/root
 - конфиги из sites-enabled
 - базу данных (только для drupal сайтов)
 - папку сайта
+- если не осталось сайтов, предлагает удалить юзера, вместе с конфигом pool.d php-fpm
 
 Не делает никаких бэкапов, осторожно!
 "
@@ -25,6 +26,7 @@ user="$(get_pwd_user)"
 nginx=$(grep -R "root $root_path;" /etc/nginx/sites-enabled | cut -d':' -f1)
 apache=$(grep -R "DocumentRoot $root_path" /etc/apache2/sites-enabled | cut -d':' -f1)
 
+# 1. Delete apache & nginx configs
 echo ""
 if [ -n "$apache" ] && [ -n "$nginx" ]; then
   read -p "Delete $nginx and $apache (y/n)? " -n 1 -r
@@ -38,6 +40,7 @@ else
   echo "Site was not enabled."
 fi
 
+# 2. Delete database
 echo ""
 database=""
 if [ -e "sites/default/settings.php" ] && [ -n $(command -v drs) ]; then
@@ -63,6 +66,7 @@ else
   echo "Database not detected."
 fi
 
+# 3. Delete site directory
 echo ""
 read -p "Delete directory $root_path (y/n)? " -n 1 -r
 echo ""
@@ -72,3 +76,32 @@ if [[ ! $REPLY =~ ^[Yy]$ ]]; then
 fi
 cd ..
 rm -rf "$root_path"
+
+# 4. Delete user if no more sites
+if [ "$(find /home/$user/www -mindepth 1 -type d | wc -l)" = 0 ]; then
+  read -p "Directory /home/$user/www is empty. Delete user $user with /home/$user (y/n)?" -n 1 -r
+  echo ""
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    echo "Aborting"
+    exit 1
+  fi
+
+  # 5. Delete php-fpm configs
+  php_fpm_configs="$(grep -R $user /etc/php | grep pool.d | grep user | cut -d':' -f1)"
+  if [ -n "$php_fpm_configs" ]; then
+    echo "User have php-fpm configs, you should delete it before user deletion:"
+    echo "$php_fpm_configs"
+    read -p "Delete php-fpm configs (y/n)?" -n 1 -r
+    echo ""
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      echo "Aborting"
+      exit 1
+    fi
+
+    echo "$php_fpm_configs" | xargs rm
+    reload-web
+
+    echo "deluser $user --remove-home"
+    deluser "$user" --remove-home
+  fi
+fi
